### ISSUE TITLE
Delete _pycache_ dir from the repository.

### ISSUE THREAD

**Issue by Alphapcka-lgtm** [buttercak3/FastAPI#1]
Delete the [_pycache_](https://github.com/buttercak3/FastAPI/tree/main/__pycache__) directory from the gir respository. It serves no purpose and git will only try to update it everytime you've built the application.

**Comment by buttercak3** [comment]
Have been too lost to get the .gitignore right 😂

**Comment by Alphapcka-lgtm** [comment]
I've fixed it in my [fork](https://github.com/Alphapcka-lgtm/FastAPI?organization=Alphapcka-lgtm&organization=Alphapcka-lgtm)
Try merging the fork into this repo

**Comment by buttercak3** [comment]
issue is fixed
